### ISSUE TITLE
[BUG]: 每次重启Bot后所有用户的可用次数会重置

### ISSUE THREAD

**Issue by ElainaFanBoy** [A-kirami/nonebot-plugin-aidraw#16]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

3e6c1eb

### 问题描述

每次重启Bot后所有用户的可用次数会重置

### 重现步骤

重启Bot

### 额外补充

不知道这是算Bug还是特性（？）

**Comment by A-kirami** [comment]
是特性，因为次数是记录在内存中，没有持久化，重启之后丢失是正常现象

**Comment by ElainaFanBoy** [comment]
> 是特性，因为次数是记录在内存中，没有持久化，重启之后丢失是正常现象

看懂了，已了解（辛苦了！）
