### ISSUE TITLE
[BUG]: 不支持nb5了吗？建议继续兼容nb5

### ISSUE THREAD

**Issue by liuzj288** [A-kirami/nonebot-plugin-aidraw#18]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

最新

### 问题描述

rc1大部分插件都还没有匹配

**Comment by Agnes4m** [comment]
建议留一个b5的版本，然后不更新了

**Comment by A-kirami** [comment]
`nonebot-plugin-aidraw` 从发布之初就是使用的 nb2 rc1 版本，从未依赖 nb2 b5，虽然理论上支持，但不会因此修改依赖项
如果你需要在 nb2 b5 中使用，在安装 `nonebot-plugin-aidraw`  之后，使用下方命令指定 nb2 版本重新安装即可

	pip install nonebot2==2.0.0b5
