### ISSUE TITLE
[BUG]: 绘画报错

### ISSUE THREAD

**Issue by Agnes4m** [A-kirami/nonebot-plugin-aidraw#19]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

0.6.0

### 问题描述

不能涩涩
![image](https://user-images.githubusercontent.com/70925546/196132402-76df2939-70d7-4c03-939c-9b47f6c60d41.png)

### 重现步骤

1、绘画 1girl

### 预期行为

正在努力绘图中……(今日剩余30次)

（假装这里有一张超涩的涩图）

### 实际行为

正在努力绘图中……(今日剩余30次)

### 日志信息

![image](https://user-images.githubusercontent.com/70925546/196132402-76df2939-70d7-4c03-939c-9b47f6c60d41.png)

### 额外补充

群里问，很快就被机器人刷走了，建议测试机器人另外拉个群

**Comment by A-kirami** [comment]
麻烦提供一下当前配置

**Comment by Agnes4m** [comment]
python3.9.13
nonebot2=2.0.0b5
nonebot-plugin-aidraw=0.6.0
pydantic=1.9.2
...
总之剩下的都是按pip安装默认的来的，只是最后改了nonebot2.0.0b5
之前0.5.0版本的时候是正常运行的

**Comment by A-kirami** [comment]
插件配置是否有做更改

**Comment by Agnes4m** [comment]
增加了token是正常的，更改了cd为30，其他没有更改

**Comment by A-kirami** [comment]
重启试试能否解决问题

**Comment by Agnes4m** [comment]
重启并没有解决，仍然是如上报错，机器人在扣扣里只会发生那第一句话

**Comment by Agnes4m** [comment]
倒版本0.5.0后，报错变了，并且bot多回复一句“出现意外的网络错误”
![image](https://user-images.githubusercontent.com/70925546/196210466-567c5527-bacd-4270-9e1b-f069009a3c30.png)

**Comment by A-kirami** [comment]
这个是 API 的原因，现在加了10s的限速了

**Comment by Agnes4m** [comment]
我认为限速应该不是主要问题，因为今天我请求了近40次，甚至换了token，也没有一次成功返回图片，也许真的这么繁忙吧。。。

**Comment by Agnes4m** [comment]
统一了两个版本下问题
0.6.1版本，回复只有 ` 正在努力绘图中……(今日剩余30次)`
![image](https://user-images.githubusercontent.com/70925546/196310108-ccdd6faf-4c08-437d-b9d1-d7050ca3e870.png)
0.5.0版本，回复同样只有 ` 正在努力绘图中……(今日剩余30次)`
```
10-18 09:00:13 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_aidraw.draw) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 688, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_aidraw/draw.py", line 142, in novel_draw_handle
    info = Image.open(BytesIO(res.content)).info
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f659fe31090>
```

没有显示list index out of range或者服务器网络错误什么的

**Comment by Agnes4m** [comment]
目前还是没有解决
已经尝试操作：更新软件，python3.9.15，倒退版本到0.4.0（报错和上0.5.0的报错一样），每次之后都重启bot
**群里发现不少人都有这个报错，看起来不像超时，像是图片发不出来**

附：0.6.1版本下完整报错
![image](https://user-images.githubusercontent.com/70925546/196328888-e32b37ac-e11b-4cd9-b8a3-b9973e970141.png)

**Comment by A-kirami** [comment]
> 统一了两个版本下问题 0.6.1版本，回复只有 ` 正在努力绘图中……(今日剩余30次)` ![image](https://user-images.githubusercontent.com/70925546/196310108-ccdd6faf-4c08-437d-b9d1-d7050ca3e870.png) 0.5.0版本，回复同样只有 ` 正在努力绘图中……(今日剩余30次)`
> 
> ```
> 10-18 09:00:13 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_aidraw.draw) failed.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "/usr/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
>     return self._bootstrap(parent_sentinel)
>   File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
>     target(sockets=sockets)
>   File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 60, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 142, in _check_matcher
>     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> > File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 186, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 716, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 688, in simple_run
>     await handler(
>   File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
>   File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_aidraw/draw.py", line 142, in novel_draw_handle
>     info = Image.open(BytesIO(res.content)).info
>   File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 3147, in open
>     raise UnidentifiedImageError(
> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f659fe31090>
> ```
> 
> 没有显示list index out of range或者服务器网络错误什么的

0.6之前的 UnidentifiedImageError 错误见 #22

**Comment by Agnes4m** [comment]
在不更新0.6.0的情况下，更换备用api解决了，谢谢大佬

**Comment by WindraiteLesd** [comment]
依旧需要解决b5版本下0.6.x版本插件主备用api都无法出图和正常使用tag排行功能并且后台报错no such table:drawcount的问题

**Comment by A-kirami** [comment]
> 依旧需要解决b5版本下0.6.x版本插件主备用api都无法出图和正常使用tag排行功能并且后台报错no such table:drawcount的问题

提供一下环境信息（操作系统，python版本）

**Comment by WindraiteLesd** [comment]
> > 依旧需要解决b5版本下0.6.x版本插件主备用api都无法出图和正常使用tag排行功能并且后台报错no such table:drawcount的问题
> 
> 提供一下环境信息（操作系统，python版本）

Windows server 2019 
python3.9.7
群里有人说0.6.2版本修好了，但是我直接clone下来使用依旧报no such table:drawcount这个错误

**Comment by A-kirami** [comment]
> > > 依旧需要解决b5版本下0.6.x版本插件主备用api都无法出图和正常使用tag排行功能并且后台报错no such table:drawcount的问题
> > 
> > 
> > 提供一下环境信息（操作系统，python版本）
> 
> Windows server 2019 python3.9.7 群里有人说0.6.2版本修好了，但是我直接clone下来使用依旧报no such table:drawcount这个错误

尝试更换3.8或者3.10看看，或者使用管理员模式运行

**Comment by Agnes4m** [comment]
linux也有一样的问题，目前0.5.0版本正常，0.6.x不行，任何指令都报错~和上放报错一样。
 ubuntu20.04,python3.9.15

**Comment by WindraiteLesd** [comment]
> linux也有一样的问题，目前0.5.0版本正常，0.6.x不行，任何指令都报错~和上放报错一样。 ubuntu20.04,python3.9.15

刚解决了，可能是数据库初始化错误的问题，你检查一下看看，我用了这个办法，如果不是的话应该可以关闭数据库解决
https://github.com/A-kirami/nonebot-plugin-aidraw/issues/34#issuecomment-1302004437
