### ISSUE TITLE
[Feature]: 请求tag记录与统计功能

### ISSUE THREAD

**Issue by liuzj288** [A-kirami/nonebot-plugin-aidraw#2]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

tag排行榜

### 您想要的解决方案

比如这样
![EK{S4TAG 90H3C4BOPEKPO1](https://user-images.githubusercontent.com/13833404/195404402-9c65f2bd-bac8-4741-845a-bf256005bf9f.PNG)

**Comment by A-kirami** [comment]
我注意到你的三个 issue 都勾选了`愿意帮助`，为了避免误解造成的时间浪费，姑且问问你是否了解该选项的含义，勾选这个表示：
**你愿意修复 bug 并实现新功能，然后将补丁提交给我**
也就是由你来负责编写代码解决这些 issue
如果你了解含义，欢迎你的pr
如果你是误解了意思，可以去掉这个选项不勾选
