### ISSUE TITLE
[BUG]: 出图报错

### ISSUE THREAD

**Issue by ShanShuWu** [A-kirami/nonebot-plugin-aidraw#22]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

0.6.1

### 问题描述

请求出图后台报错，无法正常出图，qq群里也有其他人反映该问题。

### 重现步骤

绘图 girl -p l --scale 12

### 预期行为

机器人：正在努力绘图中……(今日剩余30次)

图片

### 实际行为

机器人：正在努力绘图中……(今日剩余30次)

无图片，后台报错

### 日志信息

![image](https://user-images.githubusercontent.com/112482297/196337032-899744aa-1af3-4ff3-9ef0-6d24bc2ac858.png)

**Comment by A-kirami** [comment]
此错误是由于 API 返回的空白图像
![-230935cb9644e40b](https://user-images.githubusercontent.com/66513481/196343693-b1ac8ec7-117a-4eea-abf1-a4a45a0083c3.png)
