### ISSUE TITLE
[Feature]: 修改自带的屏蔽词

### ISSUE THREAD

**Issue by zxczaq001** [A-kirami/nonebot-plugin-aidraw#24]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

使用api的&r18=1 没有效果 应该是插件自带屏蔽了吧 没找到在哪修改

### 您想要的解决方案

添加修改默认屏蔽词的方法

**Comment by A-kirami** [comment]
没有设置任何屏蔽词或者屏蔽参数，参数的设置方法具体见 readme 部分。
&r18=1 无效的原因在于本插件不支持以 `query string` 的方式提供参数，只有以 shell 形式提供的参数经过解析之后，才会以 `params` 的形式请求 API
如果你需要添加新的处理参数，应在 `draw.py` 的 86-92行部分自行添加参数解析
