### ISSUE TITLE
[Feature]: 绘图冷却时间增加剩余时间提示

### ISSUE THREAD

**Issue by Kiana1314** [A-kirami/nonebot-plugin-aidraw#25]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

群友不知道剩余多少秒结束冷却 一直刷屏

### 您想要的解决方案

绘图冷却时间增加剩余时间提示

**Comment by A-kirami** [comment]
此项目已停止维护并归档
