### ISSUE TITLE
[Feature]: 屏蔽词不能识别以空格分隔的标签

### ISSUE THREAD

**Issue by Kiana1314** [A-kirami/nonebot-plugin-aidraw#28]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

屏蔽词不能识别以空格分隔的单词标签，而画图ai却能以空格分隔的单词或句子来作图
![image](https://user-images.githubusercontent.com/107671434/196853605-403750e3-553d-48e3-9562-e5cdd003bd0b.png)

### 您想要的解决方案

屏蔽词识别以空格分隔的单词标签

**Comment by A-kirami** [comment]
![image](https://user-images.githubusercontent.com/66513481/196854704-f7644629-9633-4615-b50d-895135afdbf2.png)
绘图正确使用方法也应该是以逗号分隔，没有逗号这就是一段短句，而不是一个个单词
说回屏蔽词，上面的是一个原因，还有一个原因就是，空格没法作为分隔符
如果以空格作为分隔符，那么两个单词乃至以上构成的组合词，就没法屏蔽了
比如:
red eyes
如果使用空格分隔，这会被拆分成两个单词 red 和 eyes
显然这是不合常理的，red 和 eyes 作为常见单词被屏蔽，影响范围太广了
