### ISSUE TITLE
[BUG]: 依赖报错安装了依赖有个报错

### ISSUE THREAD

**Issue by LSGLSH** [A-kirami/nonebot-plugin-aidraw#30]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

当前最新版本

### 问题描述

![QQ图片20221021125043](https://user-images.githubusercontent.com/106002475/197114722-63641769-dfd7-4e4a-8f63-e8f4e423f226.png)

**Comment by A-kirami** [comment]
检查是否有安装 tortoise-orm 这个依赖

**Comment by LSGLSH** [comment]
> 检查是否有安装 tortoise-orm 这个依赖

确定是安装了的

**Comment by LSGLSH** [comment]
> tortoise-orm

解决了依赖报错是错误的
他是说我没有 tortoise这个而不是没有这个 tortoise-orm

**Comment by A-kirami** [comment]
> > tortoise-orm
> 
> 解决了依赖报错是错误的
> 他是说我没有 tortoise这个而不是没有这个 tortoise-orm

tortoise-orm是包名，tortoise是导入的模块名，是一个东西
跟nonebot2安装的时候是nonebot2，导入名是nonebot一样

**Comment by LSGLSH** [comment]
> > > tortoise-orm
> > 
> > 
> > 解决了依赖报错是错误的
> > 他是说我没有 tortoise这个而不是没有这个 tortoise-orm
> 
> tortoise-orm是包名，tortoise是导入的模块名，是一个东西 跟nonebot2安装的时候是nonebot2，导入名是nonebot一样

好的，懂了
