### ISSUE TITLE
[BUG]: nonebot-plugin-aidraw成功加载后会导致LittlePaimon机器人数据库连接失败

### ISSUE THREAD

**Issue by zhulinyv** [A-kirami/nonebot-plugin-aidraw#31]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

v0.6.3

### 问题描述

如图，出现以下报错，是因为数据库冲突嘛，请问是否可以修复？
![image](https://user-images.githubusercontent.com/66541860/197336316-79f5364c-ef09-4f36-9067-8a5b368181a1.png)
![image](https://user-images.githubusercontent.com/66541860/197336336-d540daa5-2e90-42c9-99c6-eb3a70c4e5e7.png)

### 重现步骤

1.正常启动。
2.出现报错。

### 预期行为

正常启动。

### 实际行为

数据库连接失败，是冲突了嘛？

**Comment by Cvandia** [comment]
同样问题，所以我用的旧版

**Comment by A-kirami** [comment]
通过什么操作安装的
依赖列表看一下

**Comment by zhulinyv** [comment]
> 通过什么操作安装的 依赖列表看一下

使用`poetry run nb plugin install nonebot-plugin-aidraw` 安装的。

已安装的内容如下：
![image](https://user-images.githubusercontent.com/66541860/197700953-53189c62-38c9-45bb-8d35-02c902a60280.png)
![image](https://user-images.githubusercontent.com/66541860/197700971-d909aead-cf24-405d-ad55-a573af8005f4.png)
![image](https://user-images.githubusercontent.com/66541860/197701006-5df4182b-047b-4baa-bb69-dafa14f07f76.png)
![image](https://user-images.githubusercontent.com/66541860/197701035-d1dbce39-c472-4009-851c-3219da92192d.png)

**Comment by A-kirami** [comment]
看了一下 littlepaimon 的源码，那边是用的配置字典初始化数据库，导致本插件无法加载默认的数据库。
可以尝试一下，但不确定能否解决问题。

**Comment by zhulinyv** [comment]
抱歉，是否可以讲一下具体如何操作，我应该如何尝试？

**Comment by A-kirami** [comment]
> 抱歉，是否可以讲一下具体如何操作，我应该如何尝试？

应该无法在插件这边处理了，需要修改 LittlePaimon 的 database 文件夹中的 \_\_init\_\_.py 文件的第9行 [点击这里查看](https://github.com/CMHopeSunshine/LittlePaimon/blob/Bot/LittlePaimon/database/__init__.py#L9)
要在 `DATABASE` 这个字典里添加 default 这个连接配置，具体怎么填就参考它里面填的其他配置吧

**Comment by zhulinyv** [comment]
> > 抱歉，是否可以讲一下具体如何操作，我应该如何尝试？
> 
> 应该无法在插件这边处理了，需要修改 LittlePaimon 的 database 文件夹中的 __init__.py 文件的第9行 [点击这里查看](https://github.com/CMHopeSunshine/LittlePaimon/blob/Bot/LittlePaimon/database/__init__.py#L9) 要在 `DATABASE` 这个字典里添加 default 这个连接配置，具体怎么填就参考它里面填的其他配置吧

好的，了解了，谢谢

**Comment by Cvandia** [comment]
> > > 抱歉，是否可以讲一下具体如何操作，我应该如何尝试？
> > 
> > 
> > 应该无法在插件这边处理了，需要修改 LittlePaimon 的 database 文件夹中的 **init**.py 文件的第9行 [点击这里查看](https://github.com/CMHopeSunshine/LittlePaimon/blob/Bot/LittlePaimon/database/__init__.py#L9) 要在 `DATABASE` 这个字典里添加 default 这个连接配置，具体怎么填就参考它里面填的其他配置吧
> 
> 好的，了解了，谢谢

您好，请问解决了吗？小白一个，该如何编写配置呢

**Comment by A-kirami** [comment]
> > > > 抱歉，是否可以讲一下具体如何操作，我应该如何尝试？
> > > 
> > > 
> > > 应该无法在插件这边处理了，需要修改 LittlePaimon 的 database 文件夹中的 **init**.py 文件的第9行 [点击这里查看](https://github.com/CMHopeSunshine/LittlePaimon/blob/Bot/LittlePaimon/database/__init__.py?rgh-link-date=2022-10-31T09%3A46%3A55Z#L9) 要在 `DATABASE` 这个字典里添加 default 这个连接配置，具体怎么填就参考它里面填的其他配置吧
> > 
> > 
> > 好的，了解了，谢谢
> 
> 您好，请问解决了吗？小白一个，该如何编写配置呢

把 aidraw 最新提交中的数据库初始化部分的字典合并到 LittlePaimon 的 DATABASE 中即可
