### ISSUE TITLE
[BUG]: v0.6.* 会导致机器人阻塞？

### ISSUE THREAD

**Issue by zhzhongshi** [A-kirami/nonebot-plugin-aidraw#32]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

v0.6 nb2.0.0rc1

### 问题描述

我尝试安装该插件玩玩，发现不处理消息，当我尝试结束时就卡死
![image](https://user-images.githubusercontent.com/39423408/197339951-e76f21c9-33cf-44ef-8fd1-3337cc51cbab.png)
我通过pip切换到v0.5.0没有该问题
![image](https://user-images.githubusercontent.com/39423408/197340017-7fc82a9b-2228-4527-9fe6-85c2412a918b.png)

### 重现步骤

1. pip install nb-cli
2. nb create bot
3. cd bot
4. nb plugin install nonebot-plugin-aidraw
5. nb run
6. ![image](https://user-images.githubusercontent.com/39423408/197339951-e76f21c9-33cf-44ef-8fd1-3337cc51cbab.png)
7. 卡死

### 预期行为

1. pip install nb-cli
2. nb create bot
3. cd bot
4. nb plugin install nonebot-plugin-aidraw
5. nb run
6. ![image](https://user-images.githubusercontent.com/39423408/197340017-7fc82a9b-2228-4527-9fe6-85c2412a918b.png)

**Comment by koking0** [comment]
我也发现这个问题了？请问解决了么？

**Comment by A-kirami** [comment]
不处理消息具体指什么？
从你提供的图上看来，并没有连接到gocq

**Comment by koking0** [comment]
> 不处理消息具体指什么？ 从你提供的图上看来，并没有连接到gocq

我这边本来使用uvicorn做的自动reload，当我对代码做了一些更新之后，之前是可以自动reload的，但是加了这个插件之后不能自动重新reload了。

**Comment by A-kirami** [comment]
> > 不处理消息具体指什么？ 从你提供的图上看来，并没有连接到gocq
> 
> 我这边本来使用uvicorn做的自动reload，当我对代码做了一些更新之后，之前是可以自动reload的，但是加了这个插件之后不能自动重新reload了。

不能reload具体是什么表现，是报错还是无异常

**Comment by koking0** [comment]
> > > 不处理消息具体指什么？ 从你提供的图上看来，并没有连接到gocq
> > 
> > 
> > 我这边本来使用uvicorn做的自动reload，当我对代码做了一些更新之后，之前是可以自动reload的，但是加了这个插件之后不能自动重新reload了。
> 
> 不能reload具体是什么表现，是报错还是无异常

没有报错，没有异常，程序就是阻塞在那里，必须kill掉之后再重启。

**Comment by A-kirami** [comment]
> > > > 不处理消息具体指什么？ 从你提供的图上看来，并没有连接到gocq
> > > 
> > > 
> > > 我这边本来使用uvicorn做的自动reload，当我对代码做了一些更新之后，之前是可以自动reload的，但是加了这个插件之后不能自动重新reload了。
> > 
> > 
> > 不能reload具体是什么表现，是报错还是无异常
> 
> 没有报错，没有异常，程序就是阻塞在那里，必须kill掉之后再重启。

测试了一下，我这里没法复现这个现象

**Comment by zhzhongshi** [comment]
> > > > > 不处理消息具体指什么？ 从你提供的图上看来，并没有连接到gocq
> > > > 
> > > > 
> > > > 我这边本来使用uvicorn做的自动reload，当我对代码做了一些更新之后，之前是可以自动reload的，但是加了这个插件之后不能自动重新reload了。
> > > 
> > > 
> > > 不能reload具体是什么表现，是报错还是无异常
> > 
> > 
> > 没有报错，没有异常，程序就是阻塞在那里，必须kill掉之后再重启。
> 
> 测试了一下，我这里没法复现这个现象

```bash
python3.9 -m pip install virtualenv
python3.9 -m virtualenv testbot
source testbot/bin/activate
cd testbot
pip install nb-cli
nb create testbot
cd testbot
nb plugin install nonebot-plugin-aidraw
nb run

^C
```
等了很长时间不结束 只能kill -9杀掉

**Comment by koking0** [comment]
我遇到的问题如下图：
![image](https://user-images.githubusercontent.com/45281765/198869243-01e6102b-29bc-4be5-9acf-110586d826b2.png)

可以确定是nonebot_plugin_aidraw插件的问题，因为去掉之后就能够自动重载。

**Comment by koking0** [comment]
各位大佬，这个问题有解决了么？

**Comment by A-kirami** [comment]
尝试更新到 0.6.4 版本查看是否解决

**Comment by A-kirami** [comment]
已解决此问题

**Comment by koking0** [comment]
我这边的问题解决了
