### ISSUE TITLE
[Feature]: 增加可以以转发形式发送带tag的绘画

### ISSUE THREAD

**Issue by Agnes4m** [A-kirami/nonebot-plugin-aidraw#35]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

群聊长tag刷屏

### 您想要的解决方案

增加可以以转发形式发送带tag的绘画，从而使得群聊看起来清洁一些

### 您考虑过的替代方案

把图片和tag分离发送，可以选择隐藏机器人回复tag从而只出现一个图带seed，或者只是一个图

### 实现的功能是什么样的？

转发消息，或者可以自定义隐藏tag

### 还有什么要补充的吗？

p.s.希望默认可以增加一个过滤名单比如nsfw这种，我朋友因为直播看了一眼就被封直播间了）

**Comment by A-kirami** [comment]
![image](https://user-images.githubusercontent.com/66513481/198570242-9eb7b730-2549-4b1e-9aa1-fdb5a66a97af.png)
你可以用
![image](https://user-images.githubusercontent.com/66513481/198570320-2855b897-2db9-4307-91bb-a52dfd480a19.png)
或者
![image](https://user-images.githubusercontent.com/66513481/198570349-b986ce87-4d76-45bb-ac1b-9f17155f8465.png)

然后

![image](https://user-images.githubusercontent.com/66513481/198570388-3a6a3229-52e5-416e-ae5a-b54a54dcc6b6.png)

你可以用

![image](https://user-images.githubusercontent.com/66513481/198570431-040a8a45-35fe-4a2c-94f5-9115c114255b.png)
