### ISSUE TITLE
[BUG]: 自定义返图的文本好像没效果

### ISSUE THREAD

**Issue by KudouShinnyan** [A-kirami/nonebot-plugin-aidraw#39]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

0.6.3

### 问题描述

![image](https://user-images.githubusercontent.com/68854981/199700396-1b9d46cd-0880-40c7-a0ea-95bc3195e918.png)
莪的看板娘(Bot)的账号被风控, 能回消息但太长会被和谐, 太长的tag跟图片一起发送的话会失败, 所以打算在返图的时候不显示tag, 像图片那样自定义文本看起来不生效(机器人有重启了的), 虽然能用图片分离或仅图片来解决, 但莪比较期望可以不显示tag用图文混合的方式发出来

**Comment by A-kirami** [comment]
打开 nonebot2 的 debug 模式，并提供启动日志中的配置信息

**Comment by KudouShinnyan** [comment]
> 打开 nonebot2 的 debug 模式，并提供启动日志中的配置信息

[2022-11-03.log](https://github.com/A-kirami/nonebot-plugin-aidraw/files/9928239/2022-11-03.log)

[error_2022-11-03.log](https://github.com/A-kirami/nonebot-plugin-aidraw/files/9928231/error_2022-11-03.log)

**Comment by A-kirami** [comment]
需要debug日志 在 env 文件中设置日志等级为 debug
![image](https://user-images.githubusercontent.com/66513481/199720251-ccc34970-b418-4493-92d5-29b8e6707605.png)

**Comment by KudouShinnyan** [comment]
> 需要debug日志 在 env 文件中设置日志等级为 debug ![image](https://user-images.githubusercontent.com/66513481/199720251-ccc34970-b418-4493-92d5-29b8e6707605.png)

(懵了, 终端界面有带DEBUG的条目, 生成的日志文件却没有)

**Comment by A-kirami** [comment]
> > 需要debug日志 在 env 文件中设置日志等级为 debug ![image](https://user-images.githubusercontent.com/66513481/199720251-ccc34970-b418-4493-92d5-29b8e6707605.png)
> 
> (懵了, 终端界面有带DEBUG的条目, 生成的日志文件却没有)

因为bot就没保存debug日志，除非你自己写debug的日志保存代码
直接复制终端里最开始nb初始化的部分 后面的插件加载部分的日志不要

**Comment by KudouShinnyan** [comment]
> 因为bot就没保存debug日志，除非你自己写debug的日志保存代码 直接复制终端里最开始nb初始化的部分 后面的插件加载部分的日志不要

11-03 21:31:44 [SUCCESS] nonebot | NoneBot is initializing...
11-03 21:31:44 [INFO] nonebot | Current Env: dev
11-03 21:31:44 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'3381716837'}, 'nickname': {'シャルシャ', '夏露夏'}, 'command_start': {''}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=30), 'ai_draw_text': '\\n图像种子: {seed}\\n迭代步数: {steps}', 'ai_draw_token': '(保密)', 'ai_draw_cooldown': 30, 'session_running_expression': '别急呀,小真寻要宕机了!QAQ', 'debug': 'False', 'environment': 'dev', 'ai_draw_message': 'part'}
11-03 21:31:47 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"

**Comment by A-kirami** [comment]
此问题无法复现
![image](https://user-images.githubusercontent.com/66513481/199740580-2004a99d-9024-4fcc-9843-0f96ba814fa9.png)
看一下你安装的插件版本

**Comment by A-kirami** [comment]
自定义消息是 0.6.4 版本的特性，
![image](https://user-images.githubusercontent.com/66513481/199741282-061f167a-f776-4ae1-b212-08c5e9ae90a6.png)
0.6.3 版本不支持
![image](https://user-images.githubusercontent.com/66513481/199741188-799413ba-c98f-4acf-8df2-9ec69c9eaba9.png)
请更新到最新版本

**Comment by KudouShinnyan** [comment]
> 自定义消息是 0.6.4 版本的特性， ![image](https://user-images.githubusercontent.com/66513481/199741282-061f167a-f776-4ae1-b212-08c5e9ae90a6.png) 0.6.3 版本不支持 ![image](https://user-images.githubusercontent.com/66513481/199741188-799413ba-c98f-4acf-8df2-9ec69c9eaba9.png) 请更新到最新版本

![Screenshot_20221104-182933_QQ](https://user-images.githubusercontent.com/68854981/199951771-df954a0c-e435-4baf-9210-f93140355943.png)
(更新后自定义有效果了, 但\n原封不动发了出来而不是换行)

**Comment by A-kirami** [comment]
> > 自定义消息是 0.6.4 版本的特性， ![image](https://user-images.githubusercontent.com/66513481/199741282-061f167a-f776-4ae1-b212-08c5e9ae90a6.png) 0.6.3 版本不支持 ![image](https://user-images.githubusercontent.com/66513481/199741188-799413ba-c98f-4acf-8df2-9ec69c9eaba9.png) 请更新到最新版本
> 
> ![Screenshot_20221104-182933_QQ](https://user-images.githubusercontent.com/68854981/199951771-df954a0c-e435-4baf-9210-f93140355943.png) (更新后自定义有效果了, 但\n原封不动发了出来而不是换行)

此问题与本issue无关 应该另开新issue反馈
