### ISSUE TITLE
[Feature]: 添加可选群聊禁用功能

### ISSUE THREAD

**Issue by hny3494317690** [A-kirami/nonebot-plugin-aidraw#4]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

添加一个可以选择哪些群聊启用哪些禁用的功能

### 您想要的解决方案

可以在.env中添加群聊号以禁用

**Comment by jx9468** [comment]
同求一个群白名单功能，只让部分群使用，一些群滥用太容易导致风控或者封禁了😂
