### ISSUE TITLE
[QUESTION]: 一直显示错误500

### ISSUE THREAD

**Issue by Dragon-ts** [A-kirami/nonebot-plugin-aidraw#42]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

v0.7.1

### 问题描述

无法进行绘图功能
我正常地设置了token,插件也正常加载.但是当在QQ发送绘图指令时bot.py报出以下错误

`[ERROR] nonebot_plugin_aidraw | https://lulu.uedbq.xyz/got_image?token=k6yR3MhlBv4LpjKAmdo7UWbZtPQxVTOS&tags=loli&shape=Landscape 500`

### 预期行为

正常发送画出来的图片并正常回复

### 实际行为

报出错误
`[ERROR] nonebot_plugin_aidraw | https://lulu.uedbq.xyz/got_image?token=k6yR3MhlBv4LpjKAmdo7UWbZtPQxVTOS&tags=loli&shape=Landscape 500`
并发送了
`出现意外的网络错误`

### 日志信息

`11-23 16:12:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_aidraw.draw)
11-23 16:12:10 [ERROR] nonebot_plugin_aidraw | https://lulu.uedbq.xyz/got_image?token=k6yR3MhlBv4LpjKAmdo7UWbZtPQxVTOS&tags=loli&shape=Landscape 500
11-23 16:12:10 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_aidraw.draw) running complete`

**Comment by WindraiteLesd** [comment]
似乎原因是不能正常访问api，链接点进去是internal server error，bot拿不到图了所以返回出现意外的网络错误，应该不是插件的bug

**Comment by WindraiteLesd** [comment]
https://github.com/pcrbot/ai_setu/issues/9
另外路路的api地址有三个，你可以都试一试，这里面有一个就是插件默认配置的lulu.uedbq.xyz，具体是哪个我也不清楚
91.216.169.75:5010
91.217.139.190:5010
185.80.202.180:5010

**Comment by shangcheng77** [comment]
老哥们有没有还能用的api啊

**Comment by shangcheng77** [comment]
> [pcrbot/ai_setu#9](https://github.com/pcrbot/ai_setu/issues/9) 另外路路的api地址有三个，你可以都试一试，这里面有一个就是插件默认配置的lulu.uedbq.xyz，具体是哪个我也不清楚 91.216.169.75:5010 91.217.139.190:5010 185.80.202.180:5010

老哥有没有还能用的api啊

**Comment by WindraiteLesd** [comment]
> > [pcrbot/ai_setu#9](https://github.com/pcrbot/ai_setu/issues/9) 另外路路的api地址有三个，你可以都试一试，这里面有一个就是插件默认配置的lulu.uedbq.xyz，具体是哪个我也不清楚 91.216.169.75:5010 91.217.139.190:5010 185.80.202.180:5010
> 
> 老哥有没有还能用的api啊

没有，实在不行可以用colab凑合

**Comment by Dragon-ts** [comment]
感谢大家!问题已解决!

**Comment by Cvandia** [comment]
> 

所以解决方案是？

**Comment by ElainaFanBoy** [comment]
> 感谢大家!问题已解决!

解决方法能不能说一下，我也这样了...以图生图也不能用

**Comment by WindraiteLesd** [comment]
> > 感谢大家!问题已解决!
> 
> 解决方法能不能说一下，我也这样了...以图生图也不能用

这个api的以图生图寄了，文字绘图是因为官方把路路的ip限速所以经常会错误500

**Comment by WindraiteLesd** [comment]
> > 
> 
> 所以解决方案是？

没有解决方案，就看路路续不续费他novelai，最近是续费了
