### ISSUE TITLE
[BUG]: 配置里的获取token 网站已挂?

### ISSUE THREAD

**Issue by Yuelioi** [A-kirami/nonebot-plugin-aidraw#43]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

### 影响版本

0.0.0

### 问题描述

点击配置->说明->获取第三方 API 的 token

网站: https://lulu.uedbq.xyz/token 挂不挂t都无法打开(我的问题?)

浏览器: edge 火狐 chrome

环境: 手机 电脑

tz: 挂了 没挂

### 复现步骤

已述

**Comment by WindraiteLesd** [comment]
api提供者摆烂了

**Comment by Yuelioi** [comment]
> api提供者摆烂了

好滴 我以为是自己的问题
