### ISSUE TITLE
[Feature]: 用户每日次数限制/图文分发防止风控

### ISSUE THREAD

**Issue by ElainaFanBoy** [A-kirami/nonebot-plugin-aidraw#6]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [x] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

可以设置全局用户每日使用次数（每日次数刷新时间为第一张图片请求的24h后）

建议生成图片后图片和文本分开发送，可以有效防止风控（经测试有个号已经风控发不出来了）

### 您想要的解决方案

“你今天还有xx次画画次数”

图片和文字可以分开发送

**Comment by A-kirami** [comment]
这是两个不同的需求，应该分别创建不同的issue

**Comment by ElainaFanBoy** [comment]
> 这是两个不同的需求，应该分别创建不同的issue

了解了，抱歉！（下次注意，辛苦了）
