### ISSUE TITLE
[Feature]: 自定义图片尺寸

### ISSUE THREAD

**Issue by NSQX13579** [A-kirami/nonebot-plugin-aidraw#7]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [ ] 我愿意帮助实现此功能。（这会将您指定为此需求的受理人并自动创建特性分支）

### 您希望能解决什么样的问题？

能够在一定范围内自定义shape的尺寸，比如200*200--1024*1024

### 您想要的解决方案

增加自定义指令

### 您考虑过的替代方案

多增加几个固定尺寸

**Comment by A-kirami** [comment]
目前插件所使用的 API 不支持自定义图片尺寸，因此暂时无法受理此需求
